replicaCount: 1

image:
    repository: counter-api
    pullPolicy: IfNotPresent
    tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls: []

resources:
    limits:
        memory: 128Mi
    requests:
        cpu: 50m
        memory: 64Mi

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

redis:
    enabled: true
    image:
        repository: redis
        tag: "6.2.5"
    service:
        port: 6379
    resources:
        limits:
            memory: 128Mi
        requests:
            cpu: 50m
            memory: 64Mi

logging:
    level: "INFO"