apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-api.fullname" . }}
  labels:
    {{- include "counter-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "counter-api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-api.fullname" . }}-redis
  labels:
    {{- include "counter-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "counter-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}