# Redis configuration, separate from application
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: false

# Application values specifically for the Stakater chart
application:
  # Name of the application.
  applicationName: "counter-api"

  deployment:
    # Replicas to be created
    replicas: 2

    # Mount path for Volumes
    volumeMounts:
      - name: tmp-volume
        mountPath: /tmp

    # Volumes to be added to the pod
    volumes:
      - name: tmp-volume
        emptyDir: {}

    # Environment variables to be passed to the app container
    env:
      REDIS_HOST:
        value: "counter-api-redis-master"
      REDIS_PORT:
        value: "6379"

    # Image of the app container
    image:
      repository: counter-api
      tag: latest
      pullPolicy: IfNotPresent

    # Liveness and Readiness probes
    livenessProbe:
      enabled: true
      httpGet:
        path: /healthz
        port: 5000
      initialDelaySeconds: 10
      periodSeconds: 10

    readinessProbe:
      enabled: true
      httpGet:
        path: /ready
        port: 5000
      initialDelaySeconds: 10
      periodSeconds: 10

    # Resources to be defined for pod
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 0.1

  # autoscaling is used for horizonal pod autoscaling
  autoscaling:
  # enabled is a boolean flag for enabling or disabling autoscaling
    enabled: true
  # minReplicas sets the minimum number of replicas
    minReplicas: 2
  # maxReplicas sets the maximum number of replicas
    maxReplicas: 10

  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 2
  # Service object for servicing pods
  service:
    ports:
      - port: 80
        name: http
        protocol: TCP
        targetPort: 5000
    type: NodePort

  # Ingress object for exposing services (optional)
  ingress:
    enabled: true
    # Name of the ingress class
    ingressClassName: nginx
    # List of host addresses to be exposed by this Ingress
    hosts:
      - host: '{{ .Release.Name }}.local'
        paths:
        - path: /
