name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Correct version for checkout action

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Correct version for buildx action

    - name: Cache Docker layers
      uses: actions/cache@v4  # Correct version for cache action
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2  # Correct version for login action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5  # Correct version for build-push action
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Verify Docker image
      run: docker images ghcr.io/${{ github.repository }}:latest
